import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SidebarDeFi from "@/components/SidebarDeFi";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      
      <body className="h-full w-full flex bg-zinc-950 text-white">
      <SidebarDeFi></SidebarDeFi>
      <main className="flex-1 w-full min-w-0 mt-10 overflow-y-auto transition-all duration-300 pl-0 mt-15 ml-5 flex justify-start lg:justify-center ">
        {children}
      </main>

      </body>
      
    </html>
  );
}
